version: "3.7"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=Europe/paris
    volumes:
      - ${USERDIR}/docker/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${USERDIR}/docker/radarr/config:/config
      - ${USERDIR}/docker/radarr/movies:/movies #optional
      - ${USERDIR}/docker/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${USERDIR}/docker/sonarr/config:/config
      - ${USERDIR}/docker/sonarr/tv:/tv #optional
      - ${USERDIR}/docker/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${USERDIR}/docker/plex/config:/config
      - ${USERDIR}/docker/plex/transcode:/transcode
      - ${USERDIR}/docker/plex/tv:/data/tvshows
      - ${USERDIR}/docker/plex/movies:/data/movies
      - ${USERDIR}/docker/plex/video:/data/video
    ports:
      - 32400:32400
    restart: unless-stopped
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${USERDIR}/docker/bazarr/config:/config
      - ${USERDIR}/docker/bazarr/downloads:/downloads
      - ${USERDIR}/docker/bazarr/movies:/movies
      - ${USERDIR}/docker/bazarr/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${USERDIR}/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=Europe/London
      - URL=project-plex.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${Token_dns} #optional
    volumes:
      - ${USERDIR}/docker/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  